version: '3'
services:
  web:
    build:
      context: .
      dockerfile: dockerfile.web
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/html:cached
    links:
      - db
      - phpmyadmin
  db:
    build:
      context: .
      dockerfile: dockerfile.mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ../db-data:/var/lib/mysql:cached
  phpmyadmin:
    build:
      context: .
      dockerfile: dockerfile.phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
